version: "3.8"

services:
  localstack:
    container_name: localstack_terraform
    image: localstack/localstack
    #network_mode: bridge
    ports:
      - '4566:4566'      # LocalStack Edge Proxy
      #- 8081:8081
    environment:
      # - AWS_DEFAULT_REGION=ap-southeast-1
      - SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - EDGE_PORT=4566
      #- PORT_WEB_UI=8081
      #- START_WEB=1
      - LOCALSTACK_HOST:localhost
      #- LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      #- LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      #- "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"