name: 'Terraform GitHub Actions'
on:
  - pull_request
  - push

jobs:
  terraform-run-local:
    name: 'Terraform Run Local' 
    runs-on: ${{ matrix.os }}
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: cloudformation,iam,sts,ssm,s3,cloudwatch,cloudwatch-logs,lambda,dynamodb,apigateway
          DEFAULT_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: mock_access_key
          AWS_SECRET_ACCESS_KEY: mock_secret_key
        ports:
          - 4566:4566
          - 4571:4571
    strategy:
      matrix:
        os: [ubuntu-latest]
        #terraform-versions: [0.11.14, latest]
        python-version: ['3.7']
    steps:
    - uses: actions/checkout@v2
    #- name: Checkout
    - name: Run with setup-python 3.7
      uses: ./
      with:
        python-version: 3.7
    - name: Verify 3.7
      run: python src/count-row-csv-lambda.py 3.7
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      id: init
      run: terraform init
    # - name: Terraform Plan
    #   id: plan
    #   run: terraform plan 
    #   continue-on-error: true


# This is a basic workflow to help you get started with Actions
