name: 'Terraform GitHub Actions'
on:
  - pull_request
  - push

jobs:
  terraform-run-local:
    name: 'Terraform Run Local' 
    runs-on: ${{ matrix.os }}
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: cloudformation,iam,sts,ssm,s3,cloudwatch,cloudwatch-logs,lambda,dynamodb,apigateway
          DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: mock_access_key
          AWS_SECRET_ACCESS_KEY: mock_secret_key
        ports:
          - 4566:4566
          - 4571:4571
    strategy:
      matrix:
        os: [ubuntu-latest]
        #terraform-versions: [0.11.14, latest]
        # python-version: ['3.7']
    steps:
    - uses: actions/checkout@v2
    - name: Checkout
    # - uses: actions/checkout@master
    - name: Initialize Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8
          python -m pip install --upgrade pip
          pip install boto3
    - name: test install python
      run: python test_python.py 3.7
    #Steps: Run Terraform
    - uses: hashicorp/setup-terraform@v1
      name: Set up Terraform
    - name: Terraform Init
      id: init
      run: terraform -chdir=terraform/ init
    - name:  Terraform Validate
      id: validate
      run:  terraform -chdir=terraform/ validate
    - name: Terraform Plan
      id: plan
      run: terraform -chdir=terraform/ plan
    - name: Terraform Apply
      if: github.event_name == 'push'
      run:  terraform -chdir=terraform/ apply -auto-approve
    - name: Terraform Destroy
      run:  terraform -chdir=terraform/ destroy -force

      continue-on-error: true


# This is a basic workflow to help you get started with Actions
