
   
name: 'Terraform GitHub Actions'
on:
  - pull_request
  - push

jobs:
  terraform-run-local:
    name: 'Terraform Run Local' 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform init
      run: |
        terraform -chdir=terraform/ init

# This is a basic workflow to help you get started with Actions
