
   
name: 'Terraform GitHub Actions'
on:
  - pull_request
  - push

jobs:
  terraform-run-local:
    name: 'Terraform Run Local' 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: ./
    
    - name: Terraform Init 
      shell: bash
      run: terraform init
    
    - name: Terraform Format 
      shell: bash
      run: terraform fmt -check
    
    - name: Terraform Plan 
      id: plan
      shell: bash
      run: terraform plan 

    - name: Print Terraform Plan 
      shell: bash
      run: echo "${{ steps.plan.outputs.stdout }}"

# This is a basic workflow to help you get started with Actions
